### ISSUE TITLE
Multiple instances not possible?

### ISSUE THREAD

**Issue by othmar52** [esonderegger/web-audio-peak-meter#1]
Hi,
I am about to create a [stemplayer](http://www.stems-music.com/) where i need a separate volume-meter for each stem-track (drums, bass, synth, vox, ...)

After implementing your library only the last volume-meter did work. Your version is in the window scope which means that it is not able to store different variables for multiple instances, right?

I have [rewritten](https://github.com/othmar52/slimpd/blob/4ce376ffd4c018a12c6e3a71068fc06f0fb01f66/core/js/volume-meter.js) it for my personal use but i will not dare to make a pull request because it will break all current implementations: in my modified version the constructor has to be called
```js
var webAudioPeakMeter = new WebAudioPeakMeter();
```

Or does your version already support multiple instances and i had been using it wrong?

**Comment by soorajlalkg-bridge** [comment]
Hi, @othmar52 , 
Replace
`var webAudioPeakMeter = (function() {`
with
`function webAudioPeakMeter () {`
and 
```
  return {
    createMeterNode: createMeterNode,
    createMeter: createMeter,
  };
})();
```
with
```
  return {
    createMeterNode: createMeterNode,
    createMeter: createMeter,
  };
};
```
then call like below:
```
var x1 = webAudioPeakMeter();
var meterNode1 = x1.createMeterNode(sourceNode1, audioCtx1);
x1.createMeter(myMeterElement1, meterNode1, {});


var x2 = webAudioPeakMeter();
var meterNode2 = x2.createMeterNode(sourceNode2, audioCtx2);
x2.createMeter(myMeterElement2, meterNode2, {});
```
this worked for me. Hope it helps someone.

**Comment by esonderegger** [comment]
I'm sorry it's taken me so long to get to this. I believe this should now be fixed in version 2 by this PR: https://github.com/esonderegger/web-audio-peak-meter/pull/12
