### ISSUE TITLE
reset the peak reading after delay

### ISSUE THREAD

**Issue by videojedi** [esonderegger/web-audio-peak-meter#17]
Not an issue.... just wanted to say thanks for a great bit of code.

What might be a reasonable way to reset the peak reading after a small delay?

Thanks again,

Richard

**Comment by esonderegger** [comment]
Hi Richard! Thank you for suggesting this!

I believe this has been implemented in an acceptable way in https://github.com/esonderegger/web-audio-peak-meter/pull/19 - and released in version 2.1.0 - when you have a chance, please check it out and let me know what you think.

To use it, in the options object (the third parameter to `createMeter`), include something like `{ peakHoldDuration: 5000, }`, which would cause the held peak to reset after 5 seconds.

**Comment by videojedi** [comment]
Works perfectly, thank you!
