### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by othmar52** [esonderegger/web-audio-peak-meter#2]
Just wanted to let you know that i have reduced the huge amount of `else` in my modified version (@see #1 ). in case you agree with this example
```js
function badPractice(flag) {
  if (flag) {
    // one branch
  } else {
    // another branch
  }
}
function goodPractice(flag) {
  if (flag) {
    // one branch
    return;
  }
  // another branch
}
```
you can take a look at [this commit](https://github.com/othmar52/slimpd/commit/d9bd25bb5324f1d16c9ea5cf6403accd64dd4622)

**Comment by esonderegger** [comment]
Thank you for suggesting this! And I'm sorry it's taken me so long to get to this. There is now an eslint rule checking for this style and with https://github.com/esonderegger/web-audio-peak-meter/pull/12 the code base is passing the rule.

There's still room for some refactoring, and perhaps a bit too much if/else, but at least the code is now modular enough to tackle bit by bit.
