### ISSUE TITLE
Use meter with video element

### ISSUE THREAD

**Issue by osztrovszkyzs-ahrt** [esonderegger/web-audio-peak-meter#4]
Hello,
I'd like to use this audio peak meter with video element (jwplayer playing HLS stream).
Is it possible?

Regards,
Zsolt

**Comment by esonderegger** [comment]
It should work. It shouldn't matter if the video source is HLS or not - if it plays through an html5 video element, you should be able to call `audioCtx.createMediaElementSource(videoElement)`, with `audioCtx` being your web audio API context, and `videoElement` being your `<video>` element.

Please let me know if it doesn't though.

**Comment by AlexandreLicinio** [comment]
Hello, 

I did but unfortunately not working :(, i guess i did it wrong:

```
<div id="my-peak-meter" style="width: 5em; height: 20em; margin: 1em 0;">
</div>
<video id="my-video" preload="metadata" controls="controls">
    <source src="http://my_live_video_streaming.m3u8">
</video>
<script src="https://esonderegger.github.io/web-audio-peak-meter/web-audio-peak-meter-2.0.0.min.js"></script>
<script>
    var myMeterElement = document.getElementById('my-peak-meter');
    var videoElement = document.getElementById('my-video');
    var audioCtx = new window.AudioContext();
    var sourceNode = audioCtx.createMediaElementSource(videoElement);
    sourceNode.connect(audioCtx.destination);
    var meterNode = webAudioPeakMeter.createMeterNode(sourceNode, audioCtx);
    webAudioPeakMeter.createMeter(myMeterElement, meterNode, {});
    videoElement.addEventListener('play', function() {
    audioCtx.resume();
    });
</script>
```
perhaps i misunderstanding the way how to do it, it displays overt the html page:
![image](https://user-images.githubusercontent.com/10514064/108594421-33f79500-737a-11eb-91e1-8a5655f0a794.png)

thanks for your help

**Comment by integralmedia** [comment]
Same issue here, cant get a video element audio to appear in the meters, the meters render to the Div but no levels are shown.
