### ISSUE TITLE
Ability to stop/start the meter

### ISSUE THREAD

**Issue by evoyy** [esonderegger/web-audio-peak-meter#42]
Once the meter is created it runs continuously with no way to stop it, so the `paintMeter()` function is called forever, even if no audio is playing. I think it would be useful to expose a method to be able to start/stop it. Something like:

````javascript
myMeter.toggleActive()
````

**Comment by esonderegger** [comment]
Addressed in https://github.com/esonderegger/web-audio-peak-meter/pull/50
