### ISSUE TITLE
Ability to disconnect from the source node

### ISSUE THREAD

**Issue by evoyy** [esonderegger/web-audio-peak-meter#43]
I'm using the meter in a modal that can be opened and closed. When I close the modal I want to be able to disconnect it from my audio context to cleanup and not waste resources.

I know I can do this:

````javascript
myMeter.node.disconnect()
````

It would be better to not have to access internal properties. Something like:

````javascript
myMeter.disconnectSource()
````

**Comment by esonderegger** [comment]
Addressed in https://github.com/esonderegger/web-audio-peak-meter/pull/50

**Comment by evoyy** [comment]
Great solution - it works perfectly! Thanks!
