### ISSUE TITLE
maskTransition config parameter is not used

### ISSUE THREAD

**Issue by evoyy** [esonderegger/web-audio-peak-meter#44]
It seems that the mask transition value is hard-coded, so the `maskTransition` config parameter has no effect

https://github.com/esonderegger/web-audio-peak-meter/blob/e7cc9a153d951f1ad89e51c85e996261e4e6ff69/src/markup.ts#L149

**Comment by esonderegger** [comment]
Fixed in #47 and published to NPM in version [3.0.1](https://www.npmjs.com/package/web-audio-peak-meter/v/3.0.1). Thanks @evoyy !

**Comment by evoyy** [comment]
Thanks! This was more of a nitpick though . In my experiments, using a 1000ms transition time is the sweet spot. I doubt anyone would want to change this.
