### ISSUE TITLE
The web-audio-peak-meter is officially broken in latest FireFox

### ISSUE THREAD

**Issue by ghost** [esonderegger/web-audio-peak-meter#56]
Try any peak-meter instance in Firefox and then in Chrome. You will see the drastic performance issue in FF. It's moving sooo slow now, it's looks like it is about to freeze.

Please fix you beautiful peak-meter!

**Comment by esonderegger** [comment]
Thank you for alerting me to this! I just ran `mozregression` and it looks like it was broken in: https://phabricator.services.mozilla.com/D193583

It's going to take me some time to figure out why, though.

**Comment by Marcin-Fenger** [comment]
In beta release 126.0b6 it works well. Let's check it out!
