### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by KobusPost** [esonderegger/web-audio-peak-meter#9]
Can you please update the npm package? it is over 4 years old.

Could not get #6 to work due to the outdated package.

**Comment by esonderegger** [comment]
Hi @KobusPost - I just updated the [npm package](https://www.npmjs.com/package/web-audio-peak-meter) to `2.0.1` after doing some refactoring this past week. This should be working now, but please let me know if doesn't for you. Thanks for flagging!
